HARMONY-504  Create helm chart
Contrast-Security-OSS/github-runner pull request #5
Opened 2020-09-04 19:19 UTC by danquack

2020-09-04 20:08 UTC, kband requested changes
Add *.tgz to .gitignore
Remove github-runner-0.1.0.tgz from commit

2020-09-04 20:08 UTC, kband commented on .github/workflows/test.yml
> +name: Java CI with Maven
Nit: misleading name

2020-09-04 20:08 UTC, kband commented on templates/NOTES.txt
> +https://github.com/organizations/{{ .Values.config.owner }}/settings/actions
👍

2020-09-08 14:03 UTC, danquack commented on templates/NOTES.txt
> +https://github.com/organizations/{{ .Values.config.owner }}/settings/actions
There may be a programattic way to handle this, but i wasnt gonna spend a whole lot of time on it

2020-09-08 18:58 UTC, kband commented on templates/NOTES.txt
> +https://github.com/organizations/{{ .Values.config.owner }}/settings/actions
I was loving the deep link to the action runner - it always takes ages to click around to get to it otherwise

2020-09-08 18:59 UTC, kband approved these changes

2020-09-08 19:21 UTC, merged